### PR TITLE
Support for ninny json

### PR DESCRIPTION
**Pull request by kag0**
I added support for https://github.com/kag0/ninny-json, if you'll have it.

Some things shamelessly copied from the other implementations.

Sorry for the whitespace changes, my editor picked up the scalafmt config and reformatted all the files I touched. I can get rid of them if you want.

### CODE REVIEW

**Comment by hseeberger** [comment]
Cool stuff, will definitely add the nanny, eh ninny.

Could you please rebase against the latest master (if not already) and then run `sbt test:scalafmt` to make sure these formatting changes (hopefully) go away? Do not simply get rid of them, I would like to understand where they come from.

**Comment by kag0** [comment]
`sbt test:scalafmt` passes and changes no files.
Perhaps that command doesn't format `build.sbt` itself, but intellij does?

**Comment by hseeberger** [comment]
@kag0 I had to remove support for ninny from the build, because it did not pass CI, because there is no published version for Scala 2.12.

**Comment by kag0** [comment]
I haven't used SBT in a while, is there a way (that's not too much trouble) to have some projects support different scala versions than others?
Failing that, I've been meaning to add 2.12 support anyway...

**Comment by hseeberger** [comment]
I have tried to set `crossScalaVersions` to Scala 2.13 only for the ninny support, but it did not work. I might have missed something, but I had to give up. Supporting 2.12 should be a requirement anyway ;-)

**Comment by kag0** [comment]
I think it's because `akka-http-json` has 2.12 in `crossScalaVersions`, and aggregates `akka-http-ninny` so it probably either overrode the `crossScalaVersions` for ninny, or couldn't find 2.12 and got mad.
anyway :shrug: 2.12 support wasn't hard, just needed to litter imports for immutable `Seq` everywhere.

**Pull request merged**
