### PR TITLE
revert #96 

### PR DESCRIPTION
**Pull request by dhoss**
so that we don't get akka.http.scaladsl.server.RejectionError: null when something goes wrong

### CODE REVIEW

**Comment by hseeberger** [comment]
@leonardehrenfried as the author of #96, what do you think about #202 and this PR?

**Comment by leonardehrenfried** [comment]
I must admit that this was a while ago but isn't a RejectionError the correct type for when the client JSON cannot be deserialised properly? It's useful to tell two cases apart:

- the client's JSON is not valid: HTTP 400
- an exception was thrown during processing of the request: HTTP 503

Again, I haven't kept up with the development of this repo so I don't exactly know how things are handled these days, but as long as I can know what type of HTTP status code to send to the client, I'd be happy with the solution.

If the problem is the missing error message, then throwing a `IllegalArgumentException(JsError.toJson(e).toString)` isn't going to help, is it? In such a case I would argue that it's better to improve the error message rather than throwing a generic exception. Perhaps it would be enough to implement `getMessage`.

**Comment by hseeberger** [comment]
@leonardehrenfried I think the problem is that one can use this library on the client side, too, where a rejection is undefined. See #202.

**Comment by leonardehrenfried** [comment]
I see.

I don't use akka-http or play-json anymore so I don't want to block this change but since the error message is contained in PlayJsonError wouldn't it be enough to implement `getMessage` in RejectionError? The ultimate goal to give a meaningful error message, isn't it?

**Comment by hseeberger** [comment]
The point here is that the concept of a rejection is only meaningful on the server. Marshalling and unmarshalling – as supported by this library – are not restricted to the server.

**Comment by hseeberger** [comment]
@dhoss Thanks!

**Pull request merged**
