### PR TITLE
Add support for Json4s

### PR DESCRIPTION
**Pull request by btomala**
Hi,

few days ago I started looking to a project for marshallers/unmarshallers Json4s. When I found your project I decide to write some code similar to yours. 

It is splitted in two modules to avoid unnecessary dependencies in project.

Fill free to change it if you wont.

Regards,
Bartek

### CODE REVIEW

**Comment by hseeberger** [comment]
@btomala, thanks a lot for your contribution! 

There's currently a discussion going on with the Akka team to have an "official Akka community project" for JSON marshaling. That might mean the end of my project. Let's see where that goes, before we continue here ...

**Comment by btomala** [comment]
Hi, so what is your decision? Do you accept my PR? 

If not I will develop this as a different project. But I think it will be easier to maintain if it can be one project.

**Comment by gamsd** [comment]
Hi, guys. Just want to let you know that I'm pretty interested in this and would like to see it moving forward. I don't care in which project this will end up merged, I just don't like the prospect of writing one more version of this by my own.

Also, in case you need, I'm happy to help. :-)

**Comment by hseeberger** [comment]
Currently it looks like spray will be supported directly by Akka, so we need community libraries for Play, Json4s, etc. I want to wait until akka-http 1.0 to see if this still is the case. Then I will merge this PR and remove spray support. Does that work for you?

**Comment by hseeberger** [comment]
@btomala, could you please rebase your PR and also try to mimic the code in PlayJsonSupport as closely as possible (which mimics the official SprayJsonSupport)?

**Comment by btomala** [comment]
hi, I will do that in this week

**Pull request closed without merging**
