### PR TITLE
unwrap reflection exceptions to resurface require errors

### PR DESCRIPTION
**Pull request by 2beaucoup**
This is a port of https://github.com/spray/spray/issues/742.

Akka bug: https://github.com/akka/akka/issues/20658.

Just checked json4s. Possible that others are affected.

### CODE REVIEW

**Comment by hseeberger** [comment]
Nice, thanks for the contribution.

**Comment by 2beaucoup** [comment]
That was quick! I just force-pushed an update that removes unnecessary parens and adds tests for the other unmarshallers. (They all work as expected.) Maybe you like to pull them in as well.

**Comment by hseeberger** [comment]
Yes, I am quick ;-)
Next time a PR isn't yet ready for merging, please name it "WIP ..." or otherwise make it clear in the description.

**Comment by hseeberger** [comment]
@2beaucoup, I can't see your force pushed additional changes. Could you please create another PR?

**Comment by 2beaucoup** [comment]
> Next time a PR isn't yet ready for merging, please name it "WIP ..." or otherwise make it clear in the description.

Will do. Just decided to follow up on the "Possible that others are affected." part.

Changes are [here](https://github.com/2beaucoup/akka-http-json/commits/require-exceptions). I'll open another PR.

**Comment by ktoso** [comment]
Thanks a lot guys for fixing this one! :-)

**Pull request merged**
