### PR TITLE
Require Encoder instead of RootEncoder for Circe marshaller generator

### PR DESCRIPTION
**Pull request by Tvaroh**
Having `io.circe.RootEncoder` requirement is too restrictive and doesn't make sense.

### CODE REVIEW

**Comment by hseeberger** [comment]
Please rebase and push again, then the scalafmt issue should be gone.

**Comment by lomigmegard** [comment]
Hey, sorry I missed your message in Gitter.

This change is coming from @travisbrown library [circe-spray](https://github.com/circe/circe-spray/blob/master/core/src/main/scala/io/circe/spray/JsonSupport.scala#L13), as requested in #114. Note that [akka-http-spray-json](https://github.com/akka/akka-http/blob/master/akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala) is using the same pattern.

This restriction is here to allow only Json objects and arrays as top-level elements, as suggested by some old RFC. More recent ones may permit any Json value ([source](https://stackoverflow.com/questions/3833299/can-an-array-be-top-level-json-text)).

From there, I let you decide the _strictness_ you want to achieve.

**Comment by notxcain** [comment]
@Tvaroh What are usecases when you respond with non Json root? I think requiring `RootEncoder` is good.

**Comment by Tvaroh** [comment]
@notxcain I don't think I respond with something other than object/array atm. I just don't want to deal with that `RootEncoder` stuff, and my current code defines `Encoder`s for the models. And looks like recent RFC allows responding with strings, etc as well. I will question this topic differently: what exactly the `RootEncoder` restriction gives to users that it was needed to break the API?

**Comment by Tvaroh** [comment]
Correct me if I'm wrong, but [RFC 7159](https://tools.ietf.org/html/rfc7159) obsoletes RFC 4627 explicitly. And its [examples](https://tools.ietf.org/html/rfc7159#section-13) section  states that strings, numbers, booleans should be considered valid JSON text. Am I interpreting it correctly?

**Comment by Tvaroh** [comment]
My another concern is whether breaking changes (like switching to `RootEncoder` and dropping implicit `printer` from the generator) should requires major version update, i.e. `2.0.0` in this case?

**Comment by hseeberger** [comment]
@Tvaroh I don't user semantic versioning. Actually I don't care about versioning too much. If I did I would have to use a tool to verify compatibility (i.e. not break anything).

**Comment by Tvaroh** [comment]
@hseeberger I see, no problem, thanks for good work in any case.

**Pull request merged**
