### PR TITLE
Add Scala 2.13 support for uJson

### PR DESCRIPTION
**Pull request by torkelrogstad**
Copied changes from #297

### CODE REVIEW

**Comment by torkelrogstad** [comment]
Looking at this further, I see that this doesn't work for Scala 2.11. Looks like uPickle dropped Scala 2.11 in the latest release. The easy solution here is to not publish `akka-http-upickle` for 2.11. What's your thoughts on this?

**Comment by hseeberger** [comment]
We can drop support for 2.11 althgether.

**Comment by torkelrogstad** [comment]
Do you want me to change that in this PR, or is that something you want to do yourself?

**Comment by hseeberger** [comment]
Please go ahead and change it here.

**Comment by torkelrogstad** [comment]
I screwed up some git stuff, and this PR auto-closed... Before opening up a new one, are you talking about dropping 2.11 for `akka-http-json` entirely, or just for uJson module?

**Comment by plokhotnyuk** [comment]
@torkelrogstad I have managed to keep the Scala 2.11 support for uPickle in the following PR that is merged already: https://github.com/hseeberger/akka-http-json/pull/317/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR145

**Pull request closed without merging**
